M48
; DRILL file {KiCad 8.0.5} date 2025-01-08T19:59:19+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-08T19:59:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C2.375
%
G90
G05
T1
X-7.552Y-10.23
T2
X-2.89Y-17.61
X2.89Y-17.61
T3
X-10.415Y-19.436
X-9.115Y-17.185
T4
X-0.8Y12.915
X-0.8Y10.885
X6.82Y11.9
T5
X0.0Y-12.54
T6
X1.105Y14.44
X1.105Y9.36
X6.82Y14.44
X6.82Y9.36
M30
